In [1]:
import pandas as pd

In [2]:
path='Resources/Soccer2018Data.csv'

In [3]:
#read csv
df=pd.read_csv(path,low_memory=False)
df.head()

,Name,Age,Nationality,Overall,Potential,Club,Preferred Position,CAM,CB,CDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,Cristiano Ronaldo,32,Portugal,94,94,Real Madrid CF,ST,89.0,53.0,62.0,...,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,L. Messi,30,Argentina,93,93,FC Barcelona,RW,92.0,45.0,59.0,...,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,88.0
2,Neymar,25,Brazil,92,94,Paris Saint-Germain,LW,88.0,46.0,59.0,...,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,84.0
3,L. Suárez,30,Uruguay,92,92,FC Barcelona,ST,87.0,58.0,65.0,...,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
4,M. Neuer,31,Germany,92,92,FC Bayern Munich,GK,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Collect a list of all the unique values in "Preferred Position"
df["Preferred Position"].unique()

array(['ST', 'RW', 'LW', 'GK', 'CDM', 'CB', 'RM', 'CM', 'LM', 'LB', 'CAM',
       'RB', 'CF', 'RWB', 'LWB'], dtype=object)

In [8]:
# Looking only at strikers (ST) to start
df_st=df.loc[df['Preferred Position']=="ST"]
df_st.head()

,Name,Age,Nationality,Overall,Potential,Club,Preferred Position,CAM,CB,CDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,Cristiano Ronaldo,32,Portugal,94,94,Real Madrid CF,ST,89.0,53.0,62.0,...,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
3,L. Suárez,30,Uruguay,92,92,FC Barcelona,ST,87.0,58.0,65.0,...,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
5,R. Lewandowski,28,Poland,91,91,FC Bayern Munich,ST,84.0,57.0,62.0,...,58.0,57.0,78.0,62.0,87.0,82.0,88.0,84.0,61.0,88.0
9,G. Higuaín,29,Argentina,90,90,Juventus,ST,81.0,46.0,52.0,...,51.0,46.0,71.0,52.0,84.0,79.0,87.0,82.0,55.0,87.0
16,S. Agüero,29,Argentina,89,89,Manchester City,ST,85.0,44.0,54.0,...,52.0,44.0,75.0,54.0,87.0,84.0,86.0,86.0,57.0,86.0

In [15]:
#Sort the DataFrame by the values in the "ST" column to find the worst
worst=df_st.sort_values(by='ST',ascending=True)
worst.head()

,Name,Age,Nationality,Overall,Potential,Club,Preferred Position,CAM,CB,CDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
17980,L. Sackey,18,Ghana,46,64,Scunthorpe United,ST,29.0,45.0,38.0,...,40.0,45.0,30.0,38.0,29.0,30.0,31.0,29.0,38.0,31.0
17779,M. Zettl,18,Germany,50,67,SpVgg Unterhaching,ST,47.0,32.0,36.0,...,39.0,32.0,42.0,36.0,46.0,49.0,43.0,49.0,41.0,43.0
15236,O. Sowunmi,21,England,59,71,Yeovil Town,ST,35.0,58.0,47.0,...,52.0,58.0,37.0,47.0,38.0,38.0,44.0,37.0,49.0,44.0
17877,E. Mason-Clark,17,England,50,63,Barnet,ST,49.0,33.0,35.0,...,39.0,33.0,42.0,35.0,49.0,50.0,45.0,51.0,40.0,45.0
17978,J. Young,17,Scotland,46,61,Swindon Town,ST,44.0,28.0,29.0,...,31.0,28.0,38.0,29.0,45.0,42.0,45.0,44.0,32.0,45.0

In [17]:
# Reset the index so that the index is now based on the sorting locations
worst_reset=worst.reset_index(drop=True)
worst_reset

,Name,Age,Nationality,Overall,Potential,Club,Preferred Position,CAM,CB,CDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,L. Sackey,18,Ghana,46,64,Scunthorpe United,ST,29.0,45.0,38.0,...,40.0,45.0,30.0,38.0,29.0,30.0,31.0,29.0,38.0,31.0
1,M. Zettl,18,Germany,50,67,SpVgg Unterhaching,ST,47.0,32.0,36.0,...,39.0,32.0,42.0,36.0,46.0,49.0,43.0,49.0,41.0,43.0
2,O. Sowunmi,21,England,59,71,Yeovil Town,ST,35.0,58.0,47.0,...,52.0,58.0,37.0,47.0,38.0,38.0,44.0,37.0,49.0,44.0
3,E. Mason-Clark,17,England,50,63,Barnet,ST,49.0,33.0,35.0,...,39.0,33.0,42.0,35.0,49.0,50.0,45.0,51.0,40.0,45.0
4,J. Young,17,Scotland,46,61,Swindon Town,ST,44.0,28.0,29.0,...,31.0,28.0,38.0,29.0,45.0,42.0,45.0,44.0,32.0,45.0
5,F. Prohart,18,Austria,47,67,Wolfsberger AC,ST,48.0,27.0,31.0,...,33.0,27.0,41.0,31.0,48.0,47.0,46.0,49.0,35.0,46.0
6,H. Logan,18,England,53,72,Milton Keynes Dons,ST,52.0,38.0,43.0,...,43.0,38.0,50.0,43.0,50.0,52.0,47.0,51.0,44.0,47.0
7,R. Roache,17,Republic of Ireland,48,69,Blackpool,ST,43.0,27.0,29.0,...,31.0,27.0,38.0,29.0,45.0,43.0,47.0,44.0,32.0,47.0
8,M. Foy,18,England,48,68,Cambridge United,ST,47.0,31.0,34.0,...,38.0,31.0,41.0,34.0,48.0,47.0,47.0,49.0,39.0,47.0
9,P. Almqvist,17,Sweden,51,68,IFK Norrköping,ST,51.0,43.0,47.0,...,48.0,43.0,50.0,47.0,50.0,52.0,47.0,51.0,48.0,47.0
10,M. Warming,17,Denmark,51,66,Brøndby IF,ST,50.0,36.0,40.0,...,40.0,36.0,47.0,40.0,49.0,50.0,47.0,50.0,42.0,47.0
11,S. McSweeney,19,Republic of Ireland,49,59,Limerick FC,ST,48.0,29.0,34.0,...,34.0,29.0,45.0,34.0,48.0,48.0,48.0,48.0,36.0,48.0
12,F. Roepstorff,19,Denmark,51,70,FC Helsingør,ST,52.0,40.0,44.0,...,42.0,40.0,50.0,44.0,51.0,52.0,48.0,51.0,44.0,48.0
13,A. Junge,24,Denmark,50,56,FC Helsingør,ST,48.0,29.0,33.0,...,35.0,29.0,42.0,33.0,49.0,48.0,49.0,49.0,37.0,49.0
14,S. Brady,21,Australia,53,64,Brisbane Roar,ST,53.0,40.0,43.0,...,46.0,40.0,49.0,43.0,52.0,53.0,49.0,53.0,46.0,49.0
15,T. Knowles,18,England,50,71,Cambridge United,ST,46.0,33.0,33.0,...,34.0,33.0,40.0,33.0,48.0,45.0,49.0,46.0,35.0,49.0
16,J. Earl,18,England,57,69,Preston North End,ST,49.0,51.0,51.0,...,56.0,51.0,49.0,51.0,50.0,53.0,49.0,52.0,56.0,49.0
17,N. Blasucci,17,Switzerland,50,67,FC St. Gallen,ST,49.0,25.0,28.0,...,30.0,25.0,41.0,28.0,50.0,47.0,49.0,50.0,32.0,49.0
18,S. Nolan,17,Republic of Ireland,50,62,Bohemian FC,ST,49.0,33.0,36.0,...,39.0,33.0,44.0,36.0,50.0,50.0,49.0,50.0,40.0,49.0
19,S. Kogut,20,Poland,50,59,Termalica Bruk-Bet Nieciecza,ST,44.0,32.0,31.0,...,32.0,32.0,38.0,31.0,46.0,44.0,49.0,45.0,34.0,49.0
20,J. Johansson,18,Denmark,50,64,FC Nordsjælland,ST,47.0,30.0,32.0,...,32.0,30.0,41.0,32.0,48.0,46.0,49.0,47.0,34.0,49.0
21,J. McMenemy,18,England,50,64,Lincoln City,ST,45.0,30.0,31.0,...,34.0,30.0,39.0,31.0,47.0,46.0,49.0,47.0,36.0,49.0
22,A. Berisha,19,Sweden,50,65,Halmstads BK,ST,43.0,39.0,36.0,...,35.0,39.0,40.0,36.0,45.0,42.0,49.0,43.0,35.0,49.0
23,A. Rose,18,Jamaica,50,60,Grimsby Town,ST,47.0,36.0,36.0,...,40.0,36.0,42.0,36.0,49.0,48.0,49.0,49.0,40.0,49.0
24,J. Aherne,18,Republic of Ireland,50,64,Bray Wanderers,ST,48.0,34.0,35.0,...,38.0,34.0,43.0,35.0,50.0,49.0,49.0,50.0,39.0,49.0
25,A. Bruseth,18,Norway,50,62,Kristiansund BK,ST,46.0,29.0,29.0,...,32.0,29.0,39.0,29.0,48.0,46.0,49.0,48.0,33.0,49.0
26,L. Demaj,19,Germany,50,64,SV Meppen,ST,49.0,27.0,31.0,...,34.0,27.0,42.0,31.0,50.0,49.0,49.0,51.0,36.0,49.0
27,J. Gray,19,Republic of Ireland,50,60,Stevenage,ST,47.0,27.0,29.0,...,31.0,27.0,39.0,29.0,48.0,46.0,49.0,48.0,32.0,49.0
28,M. Moric,17,Australia,50,66,Newcastle Jets,ST,49.0,28.0,32.0,...,33.0,28.0,43.0,32.0,50.0,48.0,49.0,49.0,35.0,49.0
29,C. Senior,20,England,55,67,Colchester United,ST,51.0,32.0,37.0,...,41.0,32.0,45.0,37.0,52.0,54.0,49.0,54.0,43.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,O. Giroud,30,France,82,82,Arsenal,ST,75.0,55.0,59.0,...,53.0,55.0,71.0,59.0,77.0,72.0,80.0,73.0,56.0,80.0
2248,J. Hernández,29,Mexico,82,82,West Ham United,ST,76.0,46.0,51.0,...,52.0,46.0,68.0,51.0,79.0,75.0,80.0,77.0,55.0,80.0
2249,B. Dost,28,Netherlands,83,83,Sporting CP,ST,71.0,57.0,57.0,...,54.0,57.0,67.0,57.0,76.0,68.0,81.0,69.0,55.0,81.0
2250,A. Martial,21,France,82,90,Manchester United,ST,79.0,55.0,60.0,...,62.0,55.0,72.0,60.0,81.0,80.0,81.0,82.0,65.0,81.0
2251,C. Immobile,27,Italy,82,83,Lazio,ST,75.0,54.0,56.0,...,56.0,54.0,67.0,56.0,79.0,74.0,81.0,76.0,58.0,81.0
2252,Willian José,25,Brazil,82,86,Real Sociedad,ST,75.0,53.0,56.0,...,53.0,53.0,68.0,56.0,78.0,73.0,81.0,75.0,56.0,81.0
2253,T. Werner,21,Germany,82,87,RB Leipzig,ST,77.0,46.0,53.0,...,55.0,46.0,68.0,53.0,80.0,78.0,81.0,80.0,59.0,81.0
2254,K. Gameiro,30,France,83,83,Atlético Madrid,ST,80.0,51.0,59.0,...,59.0,51.0,74.0,59.0,81.0,80.0,81.0,80.0,62.0,81.0
2255,A. Belotti,23,Italy,83,90,Torino,ST,74.0,51.0,52.0,...,52.0,51.0,65.0,52.0,78.0,72.0,82.0,75.0,54.0,82.0
2256,Falcao,31,Colombia,84,84,AS Monaco,ST,77.0,54.0,57.0,...,54.0,54.0,71.0,57.0,79.0,74.0,82.0,76.0,56.0,82.0
2257,E. Džeko,31,Bosnia Herzegovina,84,84,Roma,ST,77.0,49.0,57.0,...,52.0,49.0,73.0,57.0,79.0,75.0,82.0,76.0,55.0,82.0
2258,Morata,24,Spain,84,88,Chelsea,ST,79.0,45.0,51.0,...,51.0,45.0,70.0,51.0,81.0,78.0,82.0,80.0,56.0,82.0
2259,M. Icardi,24,Argentina,84,89,Inter,ST,75.0,46.0,50.0,...,49.0,46.0,67.0,50.0,79.0,73.0,82.0,75.0,51.0,82.0
2260,K. Mbappé,18,France,83,94,Paris Saint-Germain,ST,81.0,58.0,64.0,...,64.0,58.0,75.0,64.0,82.0,81.0,82.0,82.0,67.0,82.0
2261,T. Müller,27,Germany,86,86,FC Bayern Munich,ST,81.0,58.0,65.0,...,66.0,58.0,78.0,65.0,83.0,81.0,83.0,81.0,68.0,83.0
2262,P. Dybala,23,Argentina,88,93,Juventus,ST,86.0,43.0,55.0,...,55.0,43.0,78.0,55.0,86.0,86.0,83.0,87.0,60.0,83.0
2263,A. Lacazette,26,France,85,88,Arsenal,ST,81.0,54.0,60.0,...,59.0,54.0,74.0,60.0,83.0,80.0,83.0,82.0,62.0,83.0
2264,K. Benzema,29,France,86,86,Real Madrid CF,ST,82.0,44.0,52.0,...,51.0,44.0,72.0,52.0,84.0,80.0,83.0,83.0,56.0,83.0
2265,Aduriz,36,Spain,84,84,Athletic Club de Bilbao,ST,76.0,60.0,58.0,...,58.0,60.0,69.0,58.0,80.0,73.0,83.0,75.0,58.0,83.0
2266,Diego Costa,28,Spain,86,86,Chelsea,ST,76.0,57.0,60.0,...,58.0,57.0,71.0,60.0,80.0,76.0,83.0,77.0,60.0,83.0
2267,R. Lukaku,24,Belgium,86,90,Manchester United,ST,77.0,53.0,57.0,...,56.0,53.0,71.0,57.0,80.0,77.0,84.0,78.0,58.0,84.0
2268,H. Kane,23,England,86,90,Tottenham Hotspur,ST,79.0,57.0,62.0,...,60.0,57.0,74.0,62.0,82.0,78.0,84.0,79.0,62.0,84.0
2269,E. Cavani,30,Uruguay,87,87,Paris Saint-Germain,ST,80.0,58.0,62.0,...,61.0,58.0,74.0,62.0,82.0,79.0,84.0,80.0,64.0,84.0
2270,Z. Ibrahimović,35,Sweden,88,88,Manchester United,ST,83.0,52.0,60.0,...,54.0,52.0,78.0,60.0,83.0,80.0,84.0,82.0,58.0,84.0
2271,P. Aubameyang,28,Gabon,88,88,Borussia Dortmund,ST,82.0,52.0,59.0,...,62.0,52.0,74.0,59.0,84.0,83.0,85.0,84.0,65.0,85.0
2272,S. Agüero,29,Argentina,89,89,Manchester City,ST,85.0,44.0,54.0,...,52.0,44.0,75.0,54.0,87.0,84.0,86.0,86.0,57.0,86.0
2273,G. Higuaín,29,Argentina,90,90,Juventus,ST,81.0,46.0,52.0,...,51.0,46.0,71.0,52.0,84.0,79.0,87.0,82.0,55.0,87.0
2274,R. Lewandowski,28,Poland,91,91,FC Bayern Munich,ST,84.0,57.0,62.0,...,58.0,57.0,78.0,62.0,87.0,82.0,88.0,84.0,61.0,88.0
2275,L. Suárez,30,Uruguay,92,92,FC Barcelona,ST,87.0,58.0,65.0,...,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
2276,Cristiano Ronaldo,32,Portugal,94,94,Real Madrid CF,ST,89.0,53.0,62.0,...,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0

In [18]:
# Save all of the information collected on the worst striker
worst_guy=worst_reset.loc[0,:]
worst_guy

Name                          L. Sackey
Age                                  18
Nationality                       Ghana
Overall                              46
Potential                            64
Club                  Scunthorpe United
Preferred Position                   ST
CAM                                  29
CB                                   45
CDM                                  38
CF                                   29
CM                                   30
LAM                                  29
LB                                   40
LCB                                  45
LCM                                  30
LDM                                  38
LF                                   29
LM                                   30
LS                                   31
LW                                   29
LWB                                  38
RAM                                  29
RB                                   40
RCB                                  45
RCM                                  30
RDM                                  38
RF                                   29
RM                                   30
RS                                   31
RW                                   29
RWB                                  38
ST                                   31
Name: 0, dtype: object